# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
